swagger: "2.0"
info:
  description: "APIs hỗ trợ tìm, tạo, cập nhật thông tin công ty và các dịch vụ của công ty"
  version: "1.0.1"
  title: "Company"
host: "apiway.mavecons.com"
basePath: "/api"
tags:
- name: "Functions List"
schemes:
- "http"
paths:
  "/companys/count":
    get:
      tags:
      - "Functions List"
      summary: "Đếm tổng số công ty"
      parameters:
      - in: "header"
        type: "string"
        name: "Authorization"
        required: true
        
      responses:
        500:
          description: "Internal server error"
        200:
          description: "OK"
          
  "/companys/listcompany":
    get:
      tags:
      - "Functions List"
      summary: "Liệt kê danh sách thông tin của công ty có thể truyền vào keySearch hay statusID"
      parameters:
      - in: "header"
        type: "string"
        name: "Authorization"
        required: true
      - in: "header"
        type: "number"
        name: "Page"
        required: true
        default: 1
      - in: "header"
        type: "number"
        name: "Limit"
        required: true
        default: 100
      - in: "query"
        name: "keySearch"
        type: "string"
        required: true
      - in: "query"
        name: "statusID"
        type: "integer"
        required: true
        
      responses:
        500:
          description: "Internal server error"
        200:
          description: "OK"
          
  "/companys/getlistservicesbycompanyid/{companyID}":
    get:
      tags:
      - "Functions List"
      summary: "Liệt kê danh sách dịch vụ theo ID công ty"
      parameters:
      - in: "header"
        type: "string"
        name: "Authorization"
        required: true
      - in: "path"
        name: "companyID"
        type: "integer"
        required: true
      responses:
        500:
          description: "Internal server error"
        200:
          description: "OK" 
          
  "/companys/toggleservicebycompanyid/{serviceID}/{companyID}":
    put:
      tags:
      - "Internal List"
      summary: "API này được sử dụng cho chủ sở hữu để chuyển đổi bất kỳ dịch vụ nào cho bất kỳ công ty nào"
      parameters:
      - in: "header"
        type: "string"
        name: "Authorization"
        required: true
      - in: "path"
        name: "serviceID"
        type: "integer"
        required: true
      - in: "path"
        name: "companyID"
        type: "integer"
        required: true
      responses:
        500:
          description: "Internal server error"
        200:
          description: "OK" 
      
  "/companys/getdropdownlist":
    get:
      tags:
      - "Functions List"
      summary: "liệt kê những thứ cần thiết có thể hiền thị của các công ty "
      parameters:
      - in: "header"
        type: "string"
        name: "Authorization"
        required: true
        
      responses:
        500:
          description: "Internal server error"
        200:
          description: "OK"
          
  "/companys/mycompany/getlistservices":
    get:
      tags:
      - "Functions List"
      summary: "liệt kê danh sách các dịch vụ mà công ty đăng ký"
      parameters:
      - in: "header"
        type: "string"
        name: "Authorization"
        required: true
        
      responses:
        500:
          description: "Internal server error"
        200:
          description: "OK" 
          
  "/companys/mycompany/toggleservice/{serviceID}":
    post:
      tags:
      - "Functions List"
      summary: "Chuyển đổi dịch vụ công ty"
      parameters:
      - in: "header"
        type: "string"
        name: "Authorization"
        required: true
      - in: "path"
        name: "serviceID"
        type: "integer"
        required: true
      responses:
        500:
          description: "Internal server error"
        200:
          description: "OK" 
          
  "/companys/mycompany":
    get:
      tags:
      - "Functions List"
      summary: "Liệt kê thông in công ty của người truyền token vào"
      parameters:
      - in: "header"
        type: "string"
        name: "Authorization"
        required: true
        
      responses:
        500:
          description: "Internal server error"
        200:
          description: "OK" 
          
  "/companys/companybyid/{companyID}":
    get:
      tags:
      - "Functions List"
      summary: "Liệt kê những thông tin cần thiết của 1 công ty theo ID công ty"
      parameters:
      - in: "header"
        type: "string"
        name: "Authorization"
        required: true
      - in: "path"
        name: "companyID"
        type: "integer"
        required: true
      responses:
        500:
          description: "Internal server error"
        200:
          description: "OK" 
          
  "/companys/createcompany":
    post:
      tags:
      - "Functions List"
      summary: "Tạo mới 1 công ty"
      parameters:
      - in: "header"
        type: "string"
        name: "Authorization"
        required: true
      - in: "body"
        name: "Body"
        required: true
        schema:
          type: "object"
          properties:
            CompanyID:
              type: "integer"
            Logo:
              type: "string"
            CompanyName:
              type: "string"
            CompanyDescription:
              type: "string"
            Address:
              type: "string"
            Phone:
              type: "string"
            StatusID:
              type: "integer"
      
      responses:
        500:
          description: "Internal server error"
        200:
          description: "OK"
          
  "/companys/updatecompany/{companyID}":
    put:
      tags:
      - "Functions List"
      summary: "Cập nhật thông tin của công ty thông qua ID công ty"
      parameters:
      - in: "header"
        type: "string"
        name: "Authorization"
        required: true
      - in: "path"
        name: "companyID"
        type: "integer"
        required: true
      - in: "body"
        name: "Body"
        required: true
        schema:
          type: "object"
          properties:
            CompanyID:
              type: "integer"
            Logo:
              type: "string"
            CompanyName:
              type: "string"
            CompanyDescription:
              type: "string"
            Address:
              type: "string"
            Phone:
              type: "string"
            StatusID:
              type: "integer"
      
      responses:
        500:
          description: "Internal server error"
        200:
          description: "OK"
          
  "/companys/updatestatuscompany/{companyID}":
    put:
      tags:
      - "Functions List"
      summary: "Cập nhật tình trạng công ty theo ID công ty"
      parameters:
      - in: "header"
        type: "string"
        name: "Authorization"
        required: true
      - in: "path"
        name: "companyID"
        type: "integer"
        required: true
      - in: "body"
        name: "Body"
        required: true
        schema:
          type: "object"
          properties:
            StaffFullName:
              type: "string"
            StatusID:
              type: "integer"
      
      responses:
        500:
          description: "Internal server error"
        200:
          description: "OK"
          
  "/companys/search":
    post:
      tags:
      - "Functions List"
      summary: "tìm công ty thông có thể tìm bằng từ khóa"
      parameters:
      - in: "header"
        type: "string"
        name: "Authorization"
        required: true
      - in: "query"
        name: "keyword"
        type: "string"
        required: true
      
      responses:
        500:
          description: "Internal server error"
        200:
          description: "OK"